### PR TITLE
fixed some typos

### PR DESCRIPTION
**Pull request by saulable**
hey dude,

So... I changed some things around. 

When you send a request via passport, the only thing that comes back is req.user, so there will be no transfer of socketId. Have removed this middleware. 

Also, there was typos, it said io.in - should have been io.on - all working fine now though 👍

### CODE REVIEW

**Comment by funador** [comment]
Hi Saul,

If you don't have the socketId then all auth data will be broadcasted back to all connected clients. To recreate this open the app in two different browsers and then notice that the auth data is updated even if that browser has not logged in. That is why the socketId is crucial. 

I am still not convinced this is broken at the moment.  Can you open up an issue that recreates the bug you are experiencing and confirm that your certificates have been set up correctly?

Cheers

**Comment by funador** [comment]
Did a little digging on this and it seems like the certs were matching to localhost and not 127.0.0.1 so have updated the callback urls, readme and Medium post to reflect that.  Tested today with fresh certificates and is working as expected, so I am going to go ahead and close this. Thanks for looking into it.

**Comment by saulable** [comment]
Yes, all that's fine. But why is req.session.socketId coming back as undefined on callbacks from oAuth. 

auth.controller.js

I understand the socketId is critical, but it's not returning.

**Comment by funador** [comment]
The most likely culprit is a mismatch between the callback urls that are registered with the providers and where the app is being viewed from in the browser (127.0.01 vs localhost).  Could also be that your certs are not set up correctly.

**Pull request closed without merging**
